pipeline {
    agent any

    stages {
        stage('Dependencies') {
            steps {
                echo 'Retrieving dependencies..'
				sh 'cd frontend/ && npm install'
                echo 'Installation completed successfully.'
            }
        }
		stage('SonarQube analysis') {
			steps {
				echo 'Running SonarQube analysis..'
				withSonarQubeEnv('sq-main') { 
					sh "/home/yohark/utils/sonarscanner/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner"
				}
				echo 'SonarQube analysis completed successfully.'
			}
		}
        stage('Build') {
            steps {
                echo 'Building project..'
				sh 'cd frontend/ && npm run build'
                echo 'Build completed successfully.'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
				echo 'No tests implemented yet: skipping tests.'
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploying...'
				echo 'Deployment not set yet: skipping deployment.'
			}
        }
    }
}